import Head from 'next/head'
import Link from 'next/link'
import styles from './Index.module.scss'
import { motion } from 'framer-motion'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leonard Moses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className={styles.body}>
      
      
      <main className={styles.main}>

        {/* 
        <motion.h1
          initial={{ x: -100 }}
          animate={{ x: 0 }}
        >Home</motion.h1>
        */}
        
        <div className={styles.dot_container}>

          <div className={styles.dot1_container}>
            
            <Link href="/Home">
              <motion.span className={styles.dot} id={styles.dot1}
              initial={{x:0 , y:-800 }}
              animate={{x:0 , y: 0 }}
              transition={{delay: 0.4 , type: 'spring' , stiffness: 100}}
              ></motion.span>
            </Link>
          </div>

          <motion.div className={styles.dot0_container}
          initial={{x: 0 , y: 0}}
          animate={{x: 0 , y: 0}}
          >
            <motion.span className={styles.dot0} id={styles.dot0}
            initial={{x: 0 , y: 0}}
            animate={{x: 0 , y: 0}}
            transition={{}}
            ></motion.span>
          </motion.div>

          <motion.div className={styles.dot2_container}
            initial={{x:-155, y:-80}}
            animate={{x:-155, y:-80}}
            transition={{delay:0}}
            >
            <Link href='/Portfolio'>
              <motion.span className={styles.dot} id={styles.dot2}
              initial={{x:-800 , y:800}}
              animate={{x:0 , y:0}}
              transition={{delay:0.4, type: 'spring' , stiffness: 100 }}
              ></motion.span>
            </Link>
          </motion.div>

          <motion.div className={styles.dot3_container}
            initial={{x:155,y:-118}}
            animate={{x:155,y:-118 /*y: -38 is default*/}}
            transition={{delay:0}}
          > 
            <Link href='/Resume'>
              <motion.span className={styles.dot} id={styles.dot3}
              initial={{x: 800 , y:800}}
              animate={{x:0 , y:0}}
              transition={{delay:0.4, type: 'spring' , stiffness: 100 }}
              ></motion.span>
            </Link>
          </motion.div>

        </div>
        <div className={styles.name}>
          <h1>Leonard Moses</h1>
        </div>

        {/*
        <Link href='/Portfolio'><motion.button
          whileHover={{ 
            scale: 1.1,
            textShadow: "0px 0px 8px rgb(255, 255, 255)",
            boxShadow: "0px 0px 8px rgb(255, 255, 255)"
          
          }}
        >Portfolio</motion.button></Link>
        */}
        
      </main>
      </body>
    </div>
  )
}

 {/* */}
  {/* */}
   {/* */}