import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import { motion } from 'framer-motion'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <motion.h1
          initial={{ x: -100 }}
          animate={{ x: 0 }}
        >Home</motion.h1>

        <Link href='/Portfolio'><motion.button
          whileHover={{ 
            scale: 1.1,
            textShadow: "0px 0px 8px rgb(255, 255, 255)",
            boxShadow: "0px 0px 8px rgb(255, 255, 255)"
          
          }}
        >Portfolio</motion.button></Link>

      </main>

    </div>
  )
}
